export { default as CourseManagement } from "./CourseManagement"
export { default as MoocManagement } from "./MoocManagement"
export { default as Resource } from "./Resource"
export { default as CreateQuiz } from "./CreateQuiz"
export { default as QuizResults } from "./QuizResults"
export { default as Assignment } from "./Assignment"
export { default as AssignmentAnswers } from "./AssignmentAnswers"